name: icps
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  # - iminuit
  # - numba-stats
  - uncertainties
  - numdifftools
  - tqdm
  - copy
  - pandas 
  - jupyter
  - pip
  - pip:
    - plothist